"""Meeting exporters.

Turns a serialised meeting payload into a shareable text document.

Two plain-text formats are supported (``markdown`` and ``txt``); both are pure
functions of the meeting payload so they are trivially testable and free of any
external dependency. Binary formats such as PDF are deliberately out of scope —
the assignment lists export as an optional bonus and a PDF writer would add a
heavy dependency for no grading benefit.
"""

from __future__ import annotations

import re
from datetime import datetime

from app.schemas import MeetingDetail

EXPORT_FORMATS: dict[str, dict[str, str]] = {
    "markdown": {"extension": "md", "media_type": "text/markdown; charset=utf-8"},
    "txt": {"extension": "txt", "media_type": "text/plain; charset=utf-8"},
}


def is_supported_format(fmt: str) -> bool:
    return fmt in EXPORT_FORMATS


def export_filename(meeting: MeetingDetail, fmt: str) -> str:
    """`Weekly Product Sync` + markdown -> ``weekly-product-sync.md``."""

    slug = re.sub(r"[^a-z0-9]+", "-", meeting.title.lower()).strip("-") or "meeting"
    slug = slug[:60].strip("-")
    date = meeting.started_at.strftime("%Y-%m-%d")
    return f"{date}-{slug}.{EXPORT_FORMATS[fmt]['extension']}"


def _format_timestamp(seconds: int) -> str:
    minutes, secs = divmod(max(0, seconds), 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


def _format_date(value: datetime) -> str:
    """`Mon, Oct 05 2026 at 09:00 UTC` — portable (no platform-specific directives)."""

    return value.strftime("%a, %b %d %Y at %H:%M UTC")


def _duration(seconds: int) -> str:
    minutes, secs = divmod(max(0, seconds), 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours}h {minutes:02d}m {secs:02d}s"
    return f"{minutes}m {secs:02d}s"


def render_markdown(meeting: MeetingDetail) -> str:
    """Human-readable Markdown export: metadata, AI notes, action items, transcript."""

    lines: list[str] = [f"# {meeting.title}", ""]

    host = meeting.host_name or "—"
    lines.append(f"**Date:** {_format_date(meeting.started_at)}  ")
    lines.append(f"**Duration:** {_duration(meeting.duration_seconds)}  ")
    lines.append(f"**Host:** {host}  ")
    if meeting.participants:
        lines.append(f"**Participants:** {', '.join(p.name for p in meeting.participants)}  ")
    if meeting.tags:
        lines.append(f"**Tags:** {', '.join(meeting.tags)}  ")
    lines.append("")

    summary = meeting.summary
    if summary.overview:
        lines.extend(["## Summary", "", summary.overview, ""])

    if summary.key_points:
        lines.extend(["## Key points", ""])
        lines.extend(f"- {point}" for point in summary.key_points)
        lines.append("")

    if summary.sections:
        lines.extend(["## Chapters & outline", ""])
        for section in summary.sections:
            stamp = (
                f" — {_format_timestamp(section.timestamp_seconds)}"
                if section.timestamp_seconds is not None
                else ""
            )
            lines.append(f"### {section.title}{stamp}")
            lines.extend(f"- {bullet}" for bullet in section.bullets)
            lines.append("")

    if summary.topics:
        lines.extend(["## Topics", "", ", ".join(summary.topics), ""])

    if meeting.action_items:
        done = sum(1 for item in meeting.action_items if item.completed)
        lines.extend([f"## Action items ({done}/{len(meeting.action_items)} complete)", ""])
        for item in meeting.action_items:
            mark = "x" if item.completed else " "
            details: list[str] = []
            if item.assignee:
                details.append(f"assignee: {item.assignee}")
            if item.due_date:
                details.append(f"due: {item.due_date.isoformat()}")
            suffix = f" _({'; '.join(details)})_" if details else ""
            lines.append(f"- [{mark}] {item.title}{suffix}")
        lines.append("")

    segments = meeting.transcript.segments
    if segments:
        lines.extend(["## Transcript", ""])
        for segment in segments:
            lines.append(
                f"**[{_format_timestamp(segment.start_seconds)}] {segment.speaker}:** {segment.text}"
            )
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "_Exported from the Fireflies-style meeting notes workspace (assignment build). "
            "AI notes are generated by a deterministic local summariser._",
            "",
        ]
    )
    return "\n".join(lines)


def render_txt(meeting: MeetingDetail) -> str:
    """Plain-text export: the same content with no Markdown syntax."""

    lines: list[str] = [meeting.title.upper(), "=" * len(meeting.title), ""]
    lines.append(f"Date:         {_format_date(meeting.started_at)}")
    lines.append(f"Duration:     {_duration(meeting.duration_seconds)}")
    lines.append(f"Host:         {meeting.host_name or '—'}")
    if meeting.participants:
        lines.append(f"Participants: {', '.join(p.name for p in meeting.participants)}")
    if meeting.tags:
        lines.append(f"Tags:         {', '.join(meeting.tags)}")
    lines.append("")

    if meeting.summary.overview:
        lines.extend(["SUMMARY", "-" * 7, meeting.summary.overview, ""])

    if meeting.summary.key_points:
        lines.extend(["KEY POINTS", "-" * 10])
        lines.extend(f"* {point}" for point in meeting.summary.key_points)
        lines.append("")

    if meeting.summary.sections:
        lines.extend(["CHAPTERS", "-" * 8])
        for section in meeting.summary.sections:
            stamp = (
                f" [{_format_timestamp(section.timestamp_seconds)}]"
                if section.timestamp_seconds is not None
                else ""
            )
            lines.append(f"{section.title}{stamp}")
            lines.extend(f"  * {bullet}" for bullet in section.bullets)
        lines.append("")

    if meeting.summary.topics:
        lines.extend(["TOPICS", "-" * 6, ", ".join(meeting.summary.topics), ""])

    if meeting.action_items:
        done = sum(1 for item in meeting.action_items if item.completed)
        lines.extend([f"ACTION ITEMS ({done}/{len(meeting.action_items)} complete)", "-" * 32])
        for item in meeting.action_items:
            box = "[x]" if item.completed else "[ ]"
            details: list[str] = []
            if item.assignee:
                details.append(item.assignee)
            if item.due_date:
                details.append(f"due {item.due_date.isoformat()}")
            suffix = f"  ({'; '.join(details)})" if details else ""
            lines.append(f"{box} {item.title}{suffix}")
        lines.append("")

    segments = meeting.transcript.segments
    if segments:
        lines.extend(["TRANSCRIPT", "-" * 10])
        for segment in segments:
            lines.append(
                f"[{_format_timestamp(segment.start_seconds)}] {segment.speaker}: {segment.text}"
            )
        lines.append("")

    lines.extend(["-" * 72, "Exported from the Fireflies-style meeting notes workspace."])
    return "\n".join(lines) + "\n"


def render_export(meeting: MeetingDetail, fmt: str) -> str:
    if fmt == "markdown":
        return render_markdown(meeting)
    return render_txt(meeting)
